### ISSUE TITLE
store-cli get fails with out of memory when downloading a large artifact

### ISSUE THREAD

**Issue by evantorrie** [screwdriver-cd/store-cli#33]
Seeing the following backtrace when trying to download a large zipped directory structure on an instance with limited memory

```
 19:57:18 $ store-cli get ./caches --type=cache --scope=pipeline || true ; echo skipping event cache ; store-cli get ./caches --type=cache --scope=job || true
19:57:49 fatal error: runtime: out of memory
19:57:49
19:57:49 runtime stack:
19:57:49 runtime.throw(0x7b7870, 0x16)
19:57:49 	/usr/local/go/src/runtime/panic.go:608 +0x72
19:57:49 runtime.sysMap(0xc044000000, 0x40000000, 0xa87278)
19:57:49 	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
19:57:49 runtime.(*mheap).sysAlloc(0xa6dfc0, 0x40000000, 0x0, 0x0)
19:57:49 	/usr/local/go/src/runtime/malloc.go:619 +0x1c7 
```

Looking at the code, it appears the interface attempts to download all the bytes into memory before then trying to write it to a file.  Seems it would be better to pass in a io.Writer so that the bytes can be written in a stream to the destination rather than trying to store it all in memory.

**Comment by jithine** [comment]
Thank you @evantorrie for the report. Pull request with the fix is very welcome :) (https://docs.screwdriver.cd/about/contributing/)

To unblock for now, you can try increasing the memory constraint with [`screwdriver.cd/ram`](https://docs.screwdriver.cd/user-guide/configuration/annotations.html)
